### ISSUE TITLE
2.4 GHz Channels?

### ISSUE THREAD

**Issue by PolynomialDivision** [freifunk-berlin/bbb-configs#121]
Which 2.4 GHz channels should we use? We have following options:
1,6,11 or 1,5,9,13

**Comment by spolack** [comment]
It depends. If majority of the neighboring Networks are at 1-6-11, then stick to that. Otherwise use 1,5,9,13.

**Comment by Akira25** [comment]
If we wan't to keep this information, we should add this as advice to the documentation (README) Otherwise, I'd like to close this.

**Comment by PolynomialDivision** [comment]
We can close.
