### ISSUE TITLE
device name length can exceed 15 chars

### ISSUE THREAD

**Issue by PolynomialDivision** [freifunk-berlin/bbb-configs#185]
Bridge-interfaces are are prefixed with "br-", so device can exceed maximum lengths even if they are just 15 chars.

**Comment by Noki** [comment]
I ran into this today... - again. How can we make the config and image generation when this happens?

**Comment by Noki** [comment]
We have multiple interface names in the repo that are too long and therefore exceed the 15 char limit of the linux kernel. We should really detect this and fail with a notice:

mesh_perleberger36
mesh_richardplatz
mesh_whateverbla

**Comment by Noki** [comment]
The length check from https://github.com/freifunk-berlin/bbb-configs/commit/81ee7086a96d5abd1d85234a63e7feb8b7c9d824 needs to be added here as well:

https://github.com/freifunk-berlin/bbb-configs/blob/0d82ff885eb4c9f7153f8245978c4d4702fc5c51/roles/cfg_openwrt/templates/common/config/network.j2#L34
https://github.com/freifunk-berlin/bbb-configs/blob/0d82ff885eb4c9f7153f8245978c4d4702fc5c51/roles/cfg_openwrt/templates/common/config/network.j2#L73
https://github.com/freifunk-berlin/bbb-configs/blob/0d82ff885eb4c9f7153f8245978c4d4702fc5c51/roles/cfg_openwrt/templates/corerouter/config/tunnelmanager.j2#L5

In addition we should probably change the text to be more specific:

"Network name is longer than 15 characters" => "Generated inteface name exceeds the 15 characters limit of the linux kernel. Try to shorten the name to resolve this."
