### ISSUE TITLE
Implement owe transition

### ISSUE THREAD

**Issue by PolynomialDivision** [freifunk-berlin/bbb-configs#237]
Openwrt supports now openwrt transition ifname on the same phy:
https://github.com/openwrt/openwrt/commit/574539ee2cdbb3dd54086423c6dfdd19bb1c06a6

OWE Transition:
https://posts.specterops.io/war-never-changes-attacks-against-wpa3s-enhanced-open-part-2-understanding-owe-90fdc29126a1

[ToDo: add better description]

**Comment by spolack** [comment]
we should first discuss if we want this. + it requires extensive testing. i'd like to make owe working with iphones first.
