### ISSUE TITLE
Upload images

### ISSUE THREAD

**Issue by PolynomialDivision** [freifunk-berlin/bbb-configs#240]
![freifunk-mesh](https://user-images.githubusercontent.com/10708466/174321624-b43cedab-53e8-4b56-b1fb-a051e18b21bb.png)

**Comment by PolynomialDivision** [comment]
![fork](https://user-images.githubusercontent.com/10708466/174396932-74cc6367-8aca-4320-b9db-570047ef8c5b.gif)

**Comment by PolynomialDivision** [comment]
![fork](https://user-images.githubusercontent.com/10708466/174400045-2a1d045e-e0f6-4912-b7e5-766ba5c9d87a.gif)
![copylink](https://user-images.githubusercontent.com/10708466/174400050-c61ec7bf-669f-4b4d-8515-2d9a8d34939b.gif)

**Comment by Akira25** [comment]
I didn't get the point of this issue. What it is meant for?

**Comment by PolynomialDivision** [comment]
Uploading binary data for reference in markdown.
