### ISSUE TITLE
iPhone cannot connect to berlin.freifunk.net Encrypted

### ISSUE THREAD

**Issue by spolack** [freifunk-berlin/bbb-configs#296]
Device: iPhone 13 mini
Firmware: current as of 2022/07

devices shows "Verbindung zum Netzwerk berlin.freifunk.net Encrypted fehlgeschlagen"

**Comment by pktpls** [comment]
I've witnessed an issue today with an Intel AX200 card (Thinkpad w/ Fedora 36) associating with the OWE wifi, but not getting a DHCP lease, repeatedly over hours. Monkey see, monkey pull logs next time.

**Comment by spolack** [comment]
monkey had success in the meantime?

**Comment by spolack** [comment]
iphone doesnt support OWE. wontfix
