### ISSUE TITLE
unify vlan numbering

### ISSUE THREAD

**Issue by freifunkoperator** [freifunk-berlin/bbb-configs#3]
It is nice that we can manually assign vlans in our setup. However, I would like to unify the vlan numbering in backbone places.

- MGMT: 42
- Client: 40
- Mesh Links?

**Comment by spolack** [comment]
I think a general blueprint aka recommendation for backbone locations would be helpful. Altough i dont think we should configure anything of it automatically.

**Comment by spolack** [comment]
For new Locations i would propse

10+ for airmax & co mesh links
20+ for 11s
40+ DHCP Clients
42 MGMT

**Comment by Akira25** [comment]
sounds good. I'd propose to add a remark on that into the documentation (README.md).
