### ISSUE TITLE
Conntrack graphs are empty

### ISSUE THREAD

**Issue by spolack** [freifunk-berlin/bbb-configs#338]

**Comment by spolack** [comment]
See-> http://monitor.berlin.freifunk.net/detail.php?p=conntrack&t=conntrack&h=zwingli-core&s=86400

**Comment by spolack** [comment]
```
root@zwingli-core:~# wc -l /proc/net/nf_conntrack
2653 /proc/net/nf_conntrack
```

The file in procfs is present. @PolynomialDivision Do you have an idea? Could that be related to some hardening by limiting permissions?

**Comment by spolack** [comment]
@PolynomialDivision  No idea?

**Comment by FFHener** [comment]
Not to shure what fixed the problem but i checked several recently flashed devices and all show monitoring data for conntrack including zwingli.
