### ISSUE TITLE
Duplicated slashes for subdir-rendering

### ISSUE THREAD

**Issue by Noki** [freifunk-berlin/bbb-configs#36]
In main.yml the subdirs are specified with a "/" at the beginning

https://github.com/Freifunk-Spalter/bbb-configs/blob/master/roles/cfg_openwrt/tasks/main.yml#L33

In https://github.com/Freifunk-Spalter/bbb-configs/blob/master/roles/cfg_openwrt/tasks/render_subdir.yml another "/" is added before the subdir variable. This causes duplicated slashes in the path as could be seen in path warnings:

```
[WARNING]: Unable to find '/root/bbb-configs/roles/cfg_openwrt/files/ap//config' in expected paths (use -vvvvv to see paths)
```

The slashes in one of the two places needs to be removed.

**Comment by spolack** [comment]
became obsolete with 56b9dd57400e82845e52432dfa2a8a9dd983e2af
