### ISSUE TITLE
Implement Core Router to act NTP Server and make aps to use it.

### ISSUE THREAD

**Issue by spolack** [freifunk-berlin/bbb-configs#4]
We should enable ntp server per default on the core routers and find a clean way how to specify that the core router shall be used as ntp server.

maybe similar to how its done for DNS and gateway in the network definition in the location group vars.

**Comment by Noki** [comment]
NTP server is enabled for core routers and uplink gateways since https://github.com/freifunk-berlin/bbb-configs/commit/53ae1611ff3d334bede50490d0c965edc7ae4db5 now only the usage by the APs is missing.

**Comment by Noki** [comment]
This can be done the same way setting dns and gateway work, by introducing a new field "ntp" in network.yml that can be read like this: https://github.com/freifunk-berlin/bbb-configs/blob/e706067ac1b0055d32057c8b4c2ebe5056822252/roles/cfg_openwrt/templates/common/config/network.j2#L43-L48

Besides that the following must be different for APs: https://github.com/freifunk-berlin/bbb-configs/blob/53ae1611ff3d334bede50490d0c965edc7ae4db5/roles/cfg_openwrt/templates/common/config/system.j2#L21-L23
