### ISSUE TITLE
install tmux and other debug tools by default

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/bbb-configs#47]
The normal firmware has some important debug tools preinstalled. We should do the same with the ansible firmware...

**Comment by Noki** [comment]
Adding tools, while convenient, increases the size of the firmware and is often unnecessary. Since bbb-configs is aimed at more advanced users, it should be sufficient to document how packages can be added to individual locations. In addition, packages can also be installed at any time via opkg.
