### ISSUE TITLE
dragonkiez_plangarage and walde use the same subnet for DHCP

### ISSUE THREAD

**Issue by Noki** [freifunk-berlin/bbb-configs#483]
We have 2 locations that use the identical subnet for DHCP.

https://github.com/freifunk-berlin/bbb-configs/blob/master/group_vars/location_dragonkiez_plangarage/networks.yml#L20
https://github.com/freifunk-berlin/bbb-configs/blob/master/group_vars/location_walde/networks.yml#L20

**Comment by pmelange** [comment]
Fixed (and installed and running) in #484 
Original error (copy-paste) was in commit 3e2d202e991b6c705b1f22a499603f24bbbd6219
