### ISSUE TITLE
Statistics: Ohlauer and Saarbruecker are not submitting statistics

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/bbb-configs#557]
Please fix

**Comment by Noki** [comment]
Fixed with https://github.com/freifunk-berlin/bbb-configs/commit/01110038708597f87c3439fc179c0030fc8f8734 

Saarbruecker is already updated, Ohlauer still needs to be updated.

**Comment by spolack** [comment]
Just flashed ohlauer.
