### ISSUE TITLE
perleberger36-core: Please fix the management adresses

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/bbb-configs#568]
gitblame says it was @PolynomialDivision who set it up with all the assignments set to 2. 

https://github.com/freifunk-berlin/bbb-configs/blob/e83ff9f769ad4475e83d892b1eec35fddf648f72/group_vars/location_perleberger36/networks.yml#L92-L103

**Comment by Noki** [comment]
#569 fixes most of this. however two of the antennas are offline and the IPs for those remain unclear.

**Comment by pmelange** [comment]
https://wiki.freifunk.net/Berlin:Standorte:Heilige-Geist-Kirche_Moabit should have the correct info for any offline devices

**Comment by pmelange** [comment]
> https://wiki.freifunk.net/Berlin:Standorte:Heilige-Geist-Kirche_Moabit should have the correct info for any offline devices

I leave change requests.  The two "offline" devices never existed.

**Comment by pmelange** [comment]
fix via #569
