### ISSUE TITLE
Migrate locations to tunspace for reliability

### ISSUE THREAD

**Issue by Noki** [freifunk-berlin/bbb-configs#602]
The following locations still use the old wireguard tunnels which proved to be unreliable. The locations should therefore be migrated to tunspace:

- [x] elsekiehl - PR #612
- [x] muggel - PR #613
- [x] fffw_lebenshilfe -  PR #603
- [x] casa_kua - PR #614
- [x] kirchhof - PR #591
- [ ] newyorck - PR #615
- [x] suedblock - PR #593
- [x] q216 - Commit https://github.com/freifunk-berlin/bbb-configs/commit/b760917d9710a6c36d0e48095246b1cba639ab24
- [x] mahalle
- [x] borussia

Please only check of the corresponding task once the PR is merged and the location is flashed with the new firmware.

**Comment by FFHener** [comment]
As New Yorck is currently not online i think we can close this issue because we cant update it
