### ISSUE TITLE
firewall:  Using "option network 'net1 net2 net3' deprecated

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/bbb-configs#63]
The configuration for firewall zones has changed from 

```
option network 'net1 net2 net3'
```
 to:
```
list network 'net1'
list network 'net2'
list network 'net3'
```
This has been done upstream https://github.com/openwrt/openwrt/commit/3bb397c99700b4645445cc0cc0955078a7b35d02

**Comment by pmelange** [comment]
The page https://openwrt.org/docs/guide-user/firewall/firewall_configuration#zones also states that network should be in list format

**Comment by spolack** [comment]
Thank you, that would be a pretty good first issue in order to get used to jinja2.
