### ISSUE TITLE
Ansible Test Build: Better handling of locations using dashes

### ISSUE THREAD

**Issue by FFHener** [freifunk-berlin/bbb-configs#661]
The way ansible and everything works the testbuild currenly fails because of ansible-underscore-foo. If we switch it to use a wildcard this problem is solved.
[Example mlk-nk](https://github.com/freifunk-berlin/bbb-configs/actions/runs/7214128983/job/19655535111)

**Comment by Noki** [comment]
If we switch it to Wildcard k12 will also build k12-haus4 and parzelle17 will also build parzelle17-fritz. This is not really a good solution.

**Comment by FFHener** [comment]
I see your point. For the moment I will just focus on converting the other locations who doesn't have this problem.

**Comment by pktpls** [comment]
> k12 will also build k12-haus4 and parzelle17 will also build parzelle17-fritz

These are not ideal location names :-) But I'll try to make it work somehow.
