### ISSUE TITLE
corerouter: have WAN on WAN-Port

### ISSUE THREAD

**Issue by Akira25** [freifunk-berlin/bbb-configs#72]
Looks like there is currently no easy way to configure a router that acts as a core router plus providing uplink via a WAN (and tunnel) connection.

For huge setups, having a separate device doing the uplink stuff is the way to go. But for smaller setups, it would be great, if we somehow can have a role, that makes corerouter+wan-uplink.

**Comment by pmelange** [comment]
I don't see why huge setups would want to have a separate device just to do WAN connectivity.  It should be possible to set up __any__ device to provide connectivity to the Internet (whether direct, via tunneldigger, or any other tunneling tech).

**Comment by spolack** [comment]
Its not a technical limitation. For now it was simply not implemented, as the initial scope was different.

**Comment by pktpls** [comment]
The tunnelmanager integration fixes this for now
